### ISSUE TITLE
the mod will not load in the mods folder.

### ISSUE THREAD

**Issue by yiak65** [SuperMartijn642/ConnectedGlass#10]
1.16.5
- Minecraft, ...
- Connected Glass, ...

the mod is in the folder, but will not load in minecraft
...

download the current latest version for 1.16.5, and load up minecraft join a world.

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
Are you using Forge?

**Comment by SuperMartijn642** [comment]
Feel free to reply and I will reopen the issue.

**Comment by anew742** [comment]
> 
> 
> Are you using Forge?

Does it require Forge? I'm having the same issue on the vanilla launcher with Fabric, it doesn't show up in game

**Comment by SuperMartijn642** [comment]
Yes, Connected Glass is only available for Forge.

**Comment by anew742** [comment]
> 
> 
> Yes, Connected Glass is only available for Forge.

You should update the mod page, there's no mention of Forge being a requirement anywhere
