### ISSUE TITLE
[Bug] Water drips through glass ceilings

### ISSUE THREAD

**Issue by mikewk** [SuperMartijn642/ConnectedGlass#11]
**Version Info**
- Minecraft, 1.16.5
- Connected Glass, 1.0.7

**Description of the Bug**
Unlike vanilla glass, ConnectedGlass blocks will display the water drip animation if there is water above them.  This can be easily fixed by adding the "minecraft:impermeable" tag to the blocks.

**Steps to Reproduce**
1.  Build a vanilla glass ceiling under a body of water and note the lack of dripping.
2.  Replace vanilla glass with ConnectedGlass blocks.
3.  Water starts dripping

**Screenshots**
Annoyingly, I tested the fix before thinking to get a screenshot of the before behavior.

**Comment by SuperMartijn642** [comment]
Oh I didn't even realize "minecraft:impermeable" was a thing. 😅
I fixed it now in version 1.0.8 for Minecraft 1.15 and up.

Thank you for reporting the issue!
