### ISSUE TITLE
[Question] As OptiFine adds Connected Glass, is this mod useful?

### ISSUE THREAD

**Issue by Catomax262** [SuperMartijn642/ConnectedGlass#13]
I have optifine. There's an option that adds connected glass in OptiFine. Have you ever heard of OptiFine?

**Comment by SuperMartijn642** [comment]
What if I don't want all the changes that come with Optifine, but I do want to use connected glass?

Also, Connected Glass adds 3 new types of glass and does not change the vanilla glass blocks.
