### ISSUE TITLE
Can not connect to LAN server after installing this mod !

### ISSUE THREAD

**Issue by Acj-16** [SuperMartijn642/ConnectedGlass#14]
Me and my friends was playing in a LAN ( through RADMIN ) server until we install this mod, 2 of my friends can't connected anyfurther because this happen :" failed to synchronize registry data from server closing connection ". I saw u post the same issue ! And because i'm not a dev, only a player so i can't understand your code, so is there anyway for a normal person as me to solve this, thanks a lot, and sorry for my bad English

**Comment by SuperMartijn642** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/7737?fbclid=IwAR3KTJGIheskMg6vGaqgXY5M05DArcxUdXw8mTL_ZArP8-o8iEsvdPEreak
The only solution is to run your world on a local server until Forge fixes the issue.

There should be enough tutorials online for setting up a Forge server.
