### ISSUE TITLE
[Feature] Italian translation

### ISSUE THREAD

**Issue by Pyr0x1** [SuperMartijn642/ConnectedGlass#18]
Hello, I see that italian translation is missing, could it be of any use? If yes, I can start working on it!

**Comment by SuperMartijn642** [comment]
Yes, translations are always welcome. Feel free to create a pull request or just paste them here in a comment.

It might be a while before I get around to merging and releasing it though, as I'm rather busy with school at the moment and don't have much time to work on mods.

**Comment by SuperMartijn642** [comment]
I added the translations now in Connected Glass 1.1.1.

Thanks again!
