### ISSUE TITLE
Is this mod optifine mod or forge mod??

### ISSUE THREAD

**Issue by yqminecraftplayer** [SuperMartijn642/ConnectedGlass#20]
Is this mod optifine mod or forge mod??

I ask because it didnt work on forge 1.16.5.Please reply me soon.

**Comment by SuperMartijn642** [comment]
Connected Glass has nothing to do with OptiFine.

Connected Glass does not change regular glass, it adds new glass blocks with connecting textures.

**Comment by yqminecraftplayer** [comment]
So means you made a new glass not the normal glass??

**Comment by SuperMartijn642** [comment]
> Connected Glass does not change regular glass, it adds new glass blocks with connecting textures.

So yes

**Comment by yqminecraftplayer** [comment]
Ok i understand.Thanks for explain to me.

**Comment by cyberbasty2** [comment]
forge or fabric ?

**Comment by SuperMartijn642** [comment]
@cyberbasty2 Connected Glass is only available for Forge
