### ISSUE TITLE
[Crash] ... When loading the game, before the main menu screen.

### ISSUE THREAD

**Issue by A5TC** [SuperMartijn642/ConnectedGlass#24]
**Version Info**
- Minecraft, 1.18.2
- Connected Glass, 1.1.4+4

**Steps to Reproduce**
 loading the game

**Crash report (~/logs/latest.log)**
...
https://bytebin.lucko.me/F48pZvkfSl

**Comment by A5TC** [comment]
FYI there is over 230+ mods in my custom pack

**Comment by A5TC** [comment]
![image](https://user-images.githubusercontent.com/37918654/172760374-dc711cc1-2489-4a95-8a01-32c9a5b7e0f8.png)

**Comment by A5TC** [comment]
https://crashy.net/ONuptVPXRgjoX0knXAlV

**Comment by SuperMartijn642** [comment]
This is caused by a change introduced in Forge 40.1.43. Probably an easy fix when I have some time.

**Comment by SuperMartijn642** [comment]
I think this is a duplicate of #23 and should already be fixed in 1.1.3a.

> Connected Glass, 1.1.4+4

'1.1.4+4' is not a version of Connected Glass 🤔 What version of Connected Glass are you using?

**Comment by A5TC** [comment]
I just realised I posted to the wrong Github. My bad.
