### ISSUE TITLE
IDynamicBakedModel Crash

### ISSUE THREAD

**Issue by Gamemassa** [SuperMartijn642/ConnectedGlass#26]
**Version Info**
- Minecraft: 1.19
- Forge: 41.0.85
- Connected Glass: 1.1.4 (Latest)

Hi,

I got an error message saying ConnectedGlass had encountered a IDynamicBakedModel issue. I've attached the crash report here.

 
[crash-2022-07-09_16.44.53-fml.txt](https://github.com/SuperMartijn642/ConnectedGlass/files/9077897/crash-2022-07-09_16.44.53-fml.txt)

**Comment by SuperMartijn642** [comment]
Fixed in Connected Glass 1.1.4b for Minecraft 1.19.
Thank you for reporting the issue!
