### ISSUE TITLE
Minor Texture Bug

### ISSUE THREAD

**Issue by GermanCheetah** [SuperMartijn642/ConnectedGlass#28]
- Minecraft 1.18.2
- Connected Glass 1.1.4

when placing clear dyed glass as shown in the screenshot, a dot in the texture will appear, it doesnt always happen, orientation seems to matter, and the dot only appears on top and on the underside

i believe this happens when the connected glass forms any shape other than a rectangle

![2022-09-09_17 29 06](https://user-images.githubusercontent.com/93001900/189388040-3a323cd9-c8ee-446d-9017-f4d4bae90f15.png)

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.1.5.

Thank you for reporting the issue!
