### ISSUE TITLE
[Bug] Glass doesn't connect on chunk borders

### ISSUE THREAD

**Issue by Worgeen** [SuperMartijn642/ConnectedGlass#29]
**Version Info**
connectedglass-1.1.4-forge-mc1.18.jar
- Minecraft 1.18.2
- Connected Glass Issue

**Description of the Bug**
Connected glasses don't connect very well between chunks

**Steps to Reproduce**
Put two (or more) connected glass in two different chunks
**Screenshots**
![image](https://user-images.githubusercontent.com/92705554/201720671-27ec05b0-852e-4cbf-918b-6c966d7b9c57.png)
![image](https://user-images.githubusercontent.com/92705554/201720692-01c2f149-6917-467f-8adf-7b7418a67f5c.png)
(looking from the bottom)
![image](https://user-images.githubusercontent.com/92705554/201720846-64382920-f77b-4c6e-9fe7-ea8fb61f1687.png)
![image](https://user-images.githubusercontent.com/92705554/201720880-6dd1e9ba-ea7e-4078-80a2-6e703c95ad3c.png)

**Comment by SuperMartijn642** [comment]
I cannot reproduce this, so it might have been fixed at some point or might be caused by some other mod.
If the issue still occurs, please create a new issue with the mods needed to reproduce it.
Anyways, thank you for reporting the issue at least!
