### ISSUE TITLE
Breaking Particles

### ISSUE THREAD

**Issue by LaidBackSloth** [SuperMartijn642/ConnectedGlass#30]
**Version Info**
- Minecraft, 1.18.2
- Connected Glass, 1.1.4

**Description of the Bug**
Breaking particles show the entire texture file, not only the 16x in the top left corner of it.

**Steps to Reproduce**
Break a block (pretty self-explanatory)

**Screenshots**
![2022-11-16_18 41 03](https://user-images.githubusercontent.com/109034679/202253939-4e2ee786-a8b3-4965-85c1-9454490100ed.png)

**Comment by SuperMartijn642** [comment]
Whoops forgot to report here, but this did get fixed at some point.
Thank you for reporting the issue!
