### ISSUE TITLE
[Feature] Compatible with Sodium without using Indium.

### ISSUE THREAD

**Issue by mn1712trungson** [SuperMartijn642/ConnectedGlass#37]
[latest.log](https://github.com/SuperMartijn642/ConnectedGlass/files/11321866/latest.log)

Currently, there is no way for me to use this mod directly with Sodium.
When both are installed, the glass is no longer connected.

**Comment by SuperMartijn642** [comment]
Nothing I can do about this, Sodium ignores Fabric's rendering api. A solution would be to install Indium.
