### ISSUE TITLE
Doesn't work on 1.20 [Bug] ...

### ISSUE THREAD

**Issue by TheWaterWave222** [SuperMartijn642/ConnectedGlass#39]
Using release 1.20 on sodium, lithium, indium, phosphor, fabric
- Minecraft, does not use connected glass

When i put the mod in the mods folder and load Minecraft my connected glass not working

**Steps to Reproduce**
Put mod in folder along with others and try

**Comment by SuperMartijn642** [comment]
Connected Glass does not change vanilla glass, it adds new blocks.
