### ISSUE TITLE
Compatibility Variant16x

### ISSUE THREAD

**Issue by Shockks** [SuperMartijn642/ConnectedGlass#4]
The connected glass recipe, vanilla glass in a 2x2, conflicts with the glass wall recipe from Variant16x. In my game, when making connected glass, I get the glass wall from Variant16x instead.

**Comment by SuperMartijn642** [comment]
I'll see if I can use a tag for the recipe, so you can use either the vanilla glass or the glass wall form Variant16x.

**Comment by SuperMartijn642** [comment]
I have decided against adding support for Variant16x because it adds too many glass walls and I would have to sort through them all per color and write them all down.
