### ISSUE TITLE
[Bug] Connected Glass mod is not compatible with Sodium 1.20.1

### ISSUE THREAD

**Issue by Woologic** [SuperMartijn642/ConnectedGlass#40]
**Version Info**
- Minecraft, 1.20.1
- Connected Glass, 1.1.6-fabric-mc1.20.jar

**Description of the Bug**
The connected glass blocks simply don't connect when sodium is enabled

**Steps to Reproduce**
Install the Connected Glass mod and Sodium, Launch Minecraft and enter a world, place connected glass blocks

**Screenshots**
Here are 2 screenshots of the glass not connecting and with the sodium GUI on screen
![2023-06-16_12 59 34](https://github.com/SuperMartijn642/ConnectedGlass/assets/110184821/afbe6811-45fd-4536-a485-355ce3eb2e01)
![2023-06-16_13 00 25](https://github.com/SuperMartijn642/ConnectedGlass/assets/110184821/27723fec-3969-456b-806d-2eb48b754c63)

**Comment by SuperMartijn642** [comment]
Sodium replaces the vanilla renderer with its own which ignores the Fabric rendering API. Any mod which uses the Fabric rendering API will be broken with Sodium.

Indium is a mod which patches Sodium's renderer to support the Fabric rendering API, so you could use that. Apart from that, nothing I can do about it. It's all on Sodium's end ¯\\(o_o)/¯
