### ISSUE TITLE
[Bug] ... glass doesnt connect on newest version of mincraft

### ISSUE THREAD

**Issue by Boombox0215** [SuperMartijn642/ConnectedGlass#41]
**fabric 0.14.21**
- Minecraft, 1.20
- Connected Glass, 1.1.6

**Description of the Bug**
... textures dont connect

**Steps to Reproduce**
...just place the connecting glass next to eachother

**Screenshots**
...
![2023-07-06_16 25 32](https://github.com/SuperMartijn642/ConnectedGlass/assets/114834415/04b36924-331c-4a19-94dd-663f993afd3e)

**Comment by SuperMartijn642** [comment]
It works fine with just Connected Glass, are you using any other mods such as Sodium?

**Comment by Ez89** [comment]
It doesn't work for me either. I use Sodium and Sodium Extra, and have installed Indium so that should fix it, right?
I am however totally new to mod packs so what do i know? xD

Other mods i use is Minihud, Freecamm Fabric, Zoomify and lambdynamiclights.

**Comment by SuperMartijn642** [comment]
@Ez89 did you use the blocks added by Connected Glass?

**Comment by Ez89** [comment]
Ah, i get it now. I can access them in creative mode on my SP world. Sorry, my bad. It works just fine. 
I will see myself to the noob corner now xD.

Thx, sweet mod btw :)
