### ISSUE TITLE
[Bug] pane texture glitch

### ISSUE THREAD

**Issue by GreenForzeGaming** [SuperMartijn642/ConnectedGlass#47]
**Version Info**
1.20.1
- Connected Glass, ... 1.1.8

**Description of the Bug**
...seems like the pane tried to be a bigger resulution

**Steps to Reproduce**
...honestly dont know

**Screenshots**
...
![2023-11-12_16 28 53](https://github.com/SuperMartijn642/ConnectedGlass/assets/62345403/fe058e42-4be5-4b69-b348-60a99ab86255)

**Comment by SuperMartijn642** [comment]
Are you using Sodium and if so, do you have Indium installed?

**Comment by GreenForzeGaming** [comment]
None of the 2. Could be diagonal panes mod but i dont see how that would play with scaled textures

**Comment by SuperMartijn642** [comment]
Not sure then. It works fine with just Connected Glass installed, so it is likely some other mod you have that's causing it to break.

**Comment by SuperMartijn642** [comment]
Connected Glass 1.1.9 completely removes any of the connecting texture stuff and just uses Fusion. Fusion's models work slightly differently, so it might have an affect on this issue.
Could you test it with Connected Glass 1.1.9 and Fusion?

**Comment by GreenForzeGaming** [comment]
ive not noticed any texture glitches yet so far.
