### ISSUE TITLE
[Question] Does this work with embeddium?

### ISSUE THREAD

**Issue by c0gd1s** [SuperMartijn642/ConnectedGlass#48]
The connected glass textures don't seem to be working at all for me running forge with embeddium, not sure if there's a workaround for 1.20.1 ..I found ReforgiumRenderer which is an indium port for rubidium, but idk if that would work with embeddium, besides it's for 1.19

**Comment by SuperMartijn642** [comment]
Connected Glass should work fine with Rubidium and Embeddium.

**Comment by c0gd1s** [comment]
My bad, the blocks are working, but I'm having the same weird thing happen with the double glass panes as the last reported bug

**Comment by c0gd1s** [comment]
it's caused by incompatibility with Fuzs Diagonal Windows mod
