### ISSUE TITLE
[Request/Suggestion] Add 'stained' to all Stained Glass block registry names

### ISSUE THREAD

**Issue by Nycto97** [SuperMartijn642/ConnectedGlass#49]
**Is your feature request related to a problem? Please describe.**
Using KubeJS, I'm fetching all sorts of blocks to manually add to block.properties from my shader, so that modded blocks get rendered and 'shaded' (I guess) the same as the shader does for vanilla blocks.

I noticed when looking in JEI before I started writing a script to fetch all modded stained glass, that stained glass from this mod does not have the word 'stained' in the registry name.

**Describe the solution you'd like**
For convenience, I would like to have 'stained' added to all stained glass registry names.

**Comment by SuperMartijn642** [comment]
You can't really change the registry names as that would mean all current blocks and items in players' worlds get lost.

**Comment by Nycto97** [comment]
Good point 😅 didn't really think about that!

Either way, knowing that these blocks will never get their registry names changed, allows me to write a script, where I take into account the absence of 'stained' in Connected Glass' stained glass registry names, without having to worry that the script will break one day due to changes.

Thank you for your (fast) reply!

**Comment by Nycto97** [comment]
Good point 😅 didn't really think about that!

Either way, knowing that these blocks will never get their registry names changed, allows me to write a script, where I take into account the absence of 'stained' in Connected Glass' stained glass registry names, without having to worry that the script will break one day due to changes.

Thank you for your (fast) reply!
