### ISSUE TITLE
[Bug] My Glass is not Coneccting

### ISSUE THREAD

**Issue by Shadownamikaze16** [SuperMartijn642/ConnectedGlass#54]
**Version Info**
- Minecraft, 1.20.2
- Connected Glass, ...

**Description of the Bug**
If i place the Added glas items it wont connect it used to work when i only used it with curseforge but now i´m using mods + Shaders and it wont connect anymore

**Steps to Reproduce**
...

**Screenshots**
![image](https://github.com/SuperMartijn642/ConnectedGlass/assets/153857739/e58f10ea-6742-41f5-beab-8e428b0b8de4)

**Comment by SuperMartijn642** [comment]
Please fill in the template. What version of Connected Glass are you using?

As stated on the mod page, in case you are using Sodium, you'll have to install Indium as well. Sodium replaces the vanilla renderer with one that ignores the Fabric rendering API. Indium patches Sodium's renderer to support the Fabric rendering API.

**Comment by Shadownamikaze16** [comment]
Thx its working now the issue was that i didnt install indium ^^
