### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by Mozork01** [SuperMartijn642/ConnectedGlass#55]
Hey

Minecraft1.20.1
Fabric Loader 0.14.25
Connected Glass 1.1.10

The upper texture of the glass is not connected.
![2023-12-18_23 01 47](https://github.com/SuperMartijn642/ConnectedGlass/assets/148884018/8486f662-0a86-4ef7-9b45-6d5f6405482c)

**Comment by SuperMartijn642** [comment]
Odd, this seems to work fine for me. What glass blocks are those? Does it happen for other types as well?

**Comment by Mozork01** [comment]
I found it. The bug is caused by the Diagonal Windows mod.
I don't know if it's up to you to fix the issue.

**Comment by Mozork01** [comment]
I see that

"[Fuzss](https://github.com/Fuzss) commented [3 weeks ago](https://github.com/Fuzss/diagonalwindows/issues/11#issuecomment-1831581494)
Diagonal Windows replaces the vanilla glass pane block, but does not remove it. This is achieved by changing the block that is placed by the glass pane item. That's why glass panes placed before and after installing the mod behave differently.

I'm personally not interested in supporting any of those connected textures mods out there as many have wildly different formats."

I apologize for the inconvenience.
