### ISSUE TITLE
[Bug] connected textures dont work on feather mc

### ISSUE THREAD

**Issue by temginson** [SuperMartijn642/ConnectedGlass#56]
**Version Info**
- Minecraft, 1.20.2
- Connected Glass, 1.1.10

**Description of the Bug**
Connected textures dose not connect

**Steps to Reproduce**
...

**Screenshots**
![image](https://github.com/SuperMartijn642/ConnectedGlass/assets/132342905/845fe655-c312-466c-bb93-3b3907f993b3)

**Comment by SuperMartijn642** [comment]
Did you use the blocks added by Connected Glass?

**Comment by temginson** [comment]
yes i am and its not working

**Comment by SuperMartijn642** [comment]
Just looked up what 'feather mc' is and it seems it is a custom server written in Rust. Clearly you can't install mods on that.
If you are using that, there's no way to even install or use blocks from Connected Glass on the server.

Are you using that? Did you install Connected Glass on the server? And again, are those the blocks added by Connected Glass and not just vanilla glass?

**Comment by temginson** [comment]
nah its a minecraft 3rd party client and yes and as you can see here [cid:a54bbc0b-821b-4971-87ea-00733fbff969]
________________________________
Från: Martijn van den Brand ***@***.***>
Skickat: den 2 januari 2024 15:26
Till: SuperMartijn642/ConnectedGlass ***@***.***>
Kopia: temginson ***@***.***>; Author ***@***.***>
Ämne: Re: [SuperMartijn642/ConnectedGlass] [Bug] connected textures dont work on feather mc (Issue #56)


Just looked up what 'feather mc' is and it seems it is a custom server written in Rust. Clearly you can't install mods on that.
If you are using that, there's no way to even install or use blocks from Connected Glass on the server.

Are you using that? Did you install Connected Glass on the server? And again, are those the blocks added by Connected Glass and not just vanilla glass?

**Comment by SuperMartijn642** [comment]
Ah okay, in that case: Are you using Fabric or Forge? Are you using any other mods?

> as you can see here [cid:a54bbc0b-821b-4971-87ea-00733fbff969]

Not sure what that means 🤔

**Comment by temginson** [comment]
ah sorry the screenshot did not work 
![image](https://github.com/SuperMartijn642/ConnectedGlass/assets/132342905/b01b8257-aafd-4d17-9e09-f32aa0762fa5)
hope it dose now

**Comment by temginson** [comment]
and feather is a fabric minecraft launcher https://feathermc.com/

**Comment by SuperMartijn642** [comment]
Are you using Fabric or Forge? Are you using any other mods?

**Comment by temginson** [comment]
feather is a fabric minecraft launcher so im using other fabric mods

**Comment by SuperMartijn642** [comment]
What other mods are you using?

If you are using Sodium, you have to install Indium.
![image](https://github.com/SuperMartijn642/ConnectedGlass/assets/12382965/22d4f433-5f3b-42cd-8462-5e3e74b1be26)

**Comment by temginson** [comment]
yeah it seams that i had turn of indium and all works now thanks for the help
