### ISSUE TITLE
Mod issue

### ISSUE THREAD

**Issue by vxnn3** [SuperMartijn642/ConnectedGlass#57]
![image](https://github.com/SuperMartijn642/ConnectedGlass/assets/155408412/27dcc3b0-d1b3-4c7a-a6ac-5ab777160694)

Hi, so i downloaded the mod with everything it say it was necessary but i still have this problem. I downloaded the required mod twice and still shows, what do i need to do?

**Comment by SuperMartijn642** [comment]
You have to install Fusion like it says. Please share what mods exactly you installed.

**Comment by vxnn3** [comment]
I installed the connected glass, but i cant find 'Fusion' when i installed the mod it only had one required mod and i installed it,  so i dont know what else i need to download or where to find it

**Comment by SuperMartijn642** [comment]
It requires both Fusion and my core library.
![image](https://github.com/SuperMartijn642/ConnectedGlass/assets/12382965/ae6e1e29-df92-4ff6-8183-82234c4b1901)

You can find Fusion here: https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures

**Comment by vxnn3** [comment]
Thank you! it works now. (-:
