### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by Snattuw** [SuperMartijn642/ConnectedGlass#58]
**Version Info**
- Minecraft, 1.20.2 fabric
- Connected Glass, 1.1.11

**Description of the Bug**
Does not connect anything.

**Steps to Reproduce**
...

**Screenshots**
...
![image](https://github.com/SuperMartijn642/ConnectedGlass/assets/148977102/f5a2ae65-e57b-4db2-9c0a-e69615381356)

**Comment by ForceHose** [comment]
Same here for me, tried installing supermartijn642corelib, fusion, indium (because i have sodium). Still doesn't work


Note : I have Iris installed, that might be my problem

**Comment by SuperMartijn642** [comment]
Connected Glass does **not** change vanilla glass.

**Comment by ForceHose** [comment]
Wdym? so what does this mod do?

**Comment by SuperMartijn642** [comment]
Maybe read the mod description?

**Comment by HelpTheDummies** [comment]
@ForceHose So what the nice lad failed to explain is that in this mod you would have to craft it yourself, and then place the windows, which is genius! Hope this helps!

**Comment by SuperMartijn642** [comment]
@Snattuw This works fine with just Connected Glass installed. Please narrow down what other mods you have that are needed to reproduce the issue.
