### ISSUE TITLE
There isn't textures of de Cristals 

### ISSUE THREAD

**Issue by Falconx94** [SuperMartijn642/ConnectedGlass#59]
**Version Info**
- Minecraft: 1.20.1
- Connected Glass, ...

**Description of the Bug**
...Texture

**Steps to Reproduce**
I installed the mod along with the Fusion and Rechiseled mods, but no crystal appears, only the purple cubes that you see in the image, I even tried to reinstall them and nothing

**Screenshots**
...
![image](https://github.com/SuperMartijn642/ConnectedGlass/assets/53576554/2f4825a9-80a5-42de-9203-65f06d4cad36)

**Comment by SuperMartijn642** [comment]
Didi you install the correct Fusion mod? https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures

**Comment by Falconx94** [comment]
is in forge (47.2.20)

**Comment by Falconx94** [comment]
> Didi you install the correct Fusion mod? https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures

yes, exactly the same version

**Comment by SuperMartijn642** [comment]
Do you have another Fusion mod installed as well?

**Comment by Falconx94** [comment]
oooouu got it, is other without "connected"
