### ISSUE TITLE
Make blocks seamlessly connected with water

### ISSUE THREAD

**Issue by PlatinPython** [SuperMartijn642/ConnectedGlass#6]
When using connectedglass blocks underwater the water is showing at the side where it is touching the blocks.
A comparison between vanilla and connectedglass:

**Vanilla Glass:**
![vanilla](https://user-images.githubusercontent.com/48529807/105578432-84ca9c80-5d80-11eb-9b37-b3a2ce940e17.png)

**ConnectedGlass Glass:**
![connected_glass](https://user-images.githubusercontent.com/48529807/105578439-872cf680-5d80-11eb-97e7-842c50adb069.png)

If possible please make water behave the same when touching connectedglass blocks as it does in vanilla.

**Comment by SuperMartijn642** [comment]
This seems to be only be an issue in 1.12 and 1.14.

**Comment by SuperMartijn642** [comment]
Actually, it was only an issue in 1.14, so assume you're using that Minecraft version. (If not, please let me know)
I changed some things to make it work now in version 1.0.6a for 1.14.

Thanks for reporting the issue!

**Comment by PlatinPython** [comment]
I am on 1.15.2

**Comment by SuperMartijn642** [comment]
Yup, seems I somehow missed it last time. I also fixed it now in 1.15 with version 1.0.6a.

Thanks again!
