### ISSUE TITLE
[Bug] MoreMcmeta Emissive Textures breaks some blocks

### ISSUE THREAD

**Issue by CrimboJimbo** [SuperMartijn642/ConnectedGlass#62]
**Version Info**
- Minecraft, 1.18.2
- Connected Glass, 1.1.11

**Description of the Bug**
Clear Red Stained Glass and Connecting Red Stained Glass are not textured properly.

All other glass is correct

**Steps to Reproduce**
N/A

**Screenshots**
![javaw_jCqMPiBB2T](https://github.com/SuperMartijn642/ConnectedGlass/assets/88461252/a11cb976-79a6-4432-808b-0e44c391bf40)

Edit: I put 1.8.2 not 1.18.2 woops

**Comment by SuperMartijn642** [comment]
What modloader are you using?

**Comment by CrimboJimbo** [comment]
Forge v. 40.2.14

**Comment by SuperMartijn642** [comment]
Both appear fine if I load up Minecraft with just Connected Glass and its dependencies for Forge 1.18.
![image](https://github.com/SuperMartijn642/ConnectedGlass/assets/12382965/cba94bb4-a207-44fc-aab1-e21f6969dc73)

Could you narrow down which other mods are needed to reproduce the issue?

**Comment by WaffleDevs** [comment]
Hey! I am working on this modpack with crimbojimbo. Is there a list of mods known to be incompatible that we should look out for?

**Comment by CrimboJimbo** [comment]
I found the conflict. "MoreMcmeta Emissive Textures Plugin." This is causing the red glass texture problem. However, I have no idea why.

**Comment by SuperMartijn642** [comment]
Ah no clue why that mod would affect blocks from Connected Glass or why those two blocks specifically.
Could you report the issue to MoreMcmeta Emissive Textures?
