### ISSUE TITLE
[Feature] Diagonal Glass Pane

### ISSUE THREAD

**Issue by caio-ozolins** [SuperMartijn642/ConnectedGlass#63]
Idea to make glass panes connect diagonaly like the mod [Diagonal Windows](https://www.curseforge.com/minecraft/mc-mods/diagonal-windows)

**Comment by DanteTooMayCry** [comment]
I will also add that the glass panes could also be horizontal (like trapdoor)

**Comment by SuperMartijn642** [comment]
Not really something I want to add to Connected Glass. Connected Glass is just intended to add connecting versions of the vanilla glass blocks.
Thank you for the suggestions though!
