### ISSUE TITLE
[Bug] pack up mod for fabric doesn't have silver recipe

### ISSUE THREAD

**Issue by ninasenpaii** [SuperMartijn642/ConnectedGlass#66]
**Version Info**
- Minecraft, version 1.20.1
- packed up

**Description of the Bug**
i have mods that add silver but the recipe is not showing up in REI.
**Steps to Reproduce**
use fabric mc ver 1.20.1
have pack up
have bewitchment, clutter ,galosphere
all mods have silver ingot no recipe for backpack
**Screenshots**
...

**Comment by SuperMartijn642** [comment]
This is not the repository for Packed Up 🤔
