### ISSUE TITLE
[Bug] "FrameBlocks" connecting -  Continuation of #46

### ISSUE THREAD

**Issue by DanteTooMayCry** [SuperMartijn642/ConnectedGlass#67]
**Version Info**
- Minecraft 1.20.1 Forge 47.2.20
- Frameblocks - newest - 9.2.1
- Connected Glass - newest - 1.1.11

**Description of the Bug**

The issue was discussed in thread #46, but I see that it still doesn't connect everything. While regular blocks are not a  big problem, framed glass panes also do not connect. Same without shaders.

(In the clip I only show a few blocks)

[Wideo](https://youtu.be/hhGwMLTsDEs)

**Comment by XFactHD** [comment]
@DanteTooMayCry you need to change the config setting I mentioned in a comment on that issue to have full connected textures support on FramedBlocks blocks: https://github.com/SuperMartijn642/ConnectedGlass/issues/46#issuecomment-1813507254
