### ISSUE TITLE
[Bug] Mob spawn on glas

### ISSUE THREAD

**Issue by DerSoftwerker** [SuperMartijn642/ConnectedGlass#7]
**Version Info**
- Minecraft, 1.16.4
- Connected Glass, 1.0.6

**Description of the Bug**
Mobs are spawning on the glas, reported from my server.

**Steps to Reproduce**
Player build a Massive glas dome with connected glas, reported mobs spawning on top of it.

**Screenshots**
https://i.imgur.com/kRtRj3c.png

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.0.6a for all the Minecraft 1.16 versions.

Thank you for reporting the issue!
