### ISSUE TITLE
[Bug] ... Missing textures?

### ISSUE THREAD

**Issue by Plluly** [SuperMartijn642/ConnectedGlass#70]
**Version Info**
- Minecraft, 1.20.1
- Connected Glass, 1.1.11

**Description of the Bug**
Every type of glass this mod adds is purple and black (missing texture) for some reason..?

**Comment by SuperMartijn642** [comment]
It works fine with just Connected Glass and its dependencies installed, so it would be caused by some other mod you have. Could you narrow down which other mod is needed to reproduce the issue?
Also, what modloader are you using?

**Comment by Plluly** [comment]
I tried 2 things
I installed connected glass 1.1.6 and the textures were there
I then reinstalled the 1.1.11 one and tried it with only the necessary mods installed, and again there was missing textures.

I'm using forge 1.20.1   1-47.3.0

**Comment by FabioTP** [comment]
Same thing it's happening to me and also using forge 1.20.1

**Comment by SuperMartijn642** [comment]
It works just fine with just Connected Glass installed.
![image](https://github.com/user-attachments/assets/66e60638-ae60-4991-a5cc-23f420463d46)

**Comment by Plluly** [comment]
> It works just fine with just Connected Glass installed. ![image](https://private-user-images.githubusercontent.com/12382965/356857918-66e60638-ae60-4991-a5cc-23f420463d46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNjIyMTYsIm5iZiI6MTcyMzM2MTkxNiwicGF0aCI6Ii8xMjM4Mjk2NS8zNTY4NTc5MTgtNjZlNjA2MzgtYWU2MC00OTkxLWE1Y2MtMjNmNDIwNDYzZDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA3MzgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1OWRkZWEyNmZmMTdmZmJmYTJiNjg5OTFiN2IyYjJlNzVmYTY5Zjg0M2I2YmQ5NDVhYTg0MmU3OGQ3OWUyZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AsGllPsT0NXd2xXNAczY7TJxILvwblYqPBmRDu1An9Q)

The versions it isn't working in are 
Forge 47.3.0
Version 1.1.11

**Comment by SuperMartijn642** [comment]
I am using version 1.1.11 of Connected Glass and even using Forge 47.3.0 rather than 47.3.5, it works fine.
![image](https://github.com/user-attachments/assets/3f88a547-331b-4e4f-af05-accf840e93ba)
