### ISSUE TITLE
[Bug] White stained glass has a recipe to create every colored variant of the connecting stained glass

### ISSUE THREAD

**Issue by Tacman215** [SuperMartijn642/ConnectedGlass#73]
**Version Info**
- Minecraft, 1.12.2
- Connected Glass, 1.1.11a

**Description of the Bug**
Using JEI, a recipe with the white stained glass is listed for every variant of the colored connected stained glass, (aside from the tinted and clear). It's also there for the connecting white stained glass as well, however, that's probably intended.

If intentional, however, then there's no functional recipe to produce any other color of connecting colored stained glass using their stained glass counterparts. Every variant of the glass lists the white stained glass in the recipe, but placing 4 white stained glass in a 2x2 grid only produces the connecting yellow stained glass. Using any other color of normal stained glass doesn't work.

**Steps to Reproduce**
When placed into the crafting table in a 2x2 pattern, the white stained glass will allow you to produce 4 yellow connecting yellow stained glass. Using any other color of normal stained glass will produce no results. Using JEI, you can click on each of the connecting colored stained glass to see that each of their secondary recipes uses the white stained glass.

**Screenshots**
![Capture](https://github.com/user-attachments/assets/bea486e2-8baa-4353-9b6b-b149e88df94d)

![Capture5](https://github.com/user-attachments/assets/02b507df-91ae-43a6-8f39-973ab5485b40)

**Comment by SuperMartijn642** [comment]
I fixed the issue now in Connected Glass version 1.1.12. Thank you for reporting the issue!
