### ISSUE TITLE
[Bug] 1.20.1 OLD Breaks the texture

### ISSUE THREAD

**Issue by Krimatoria** [SuperMartijn642/ConnectedGlass#75]
Fix: The problem is solved simply by disabling your mod.

**Version Info**
- Minecraft 1.20.1
- Connectedglass-1.1.11-forge-mc1.20.1.jar

**Description of the Bug**
The old Minecraft problem with texture breaks is being reproduced. I must say right away, yes, it is not solved by adding or removing the Model Gop Fix - this is not a solution. 

The problem is only visible with shaders all over the world, it's just not so noticeable in terrestrial. With different shader settings, this effect works differently, the dots and lines will either be dimmer, static or more blurred, they may flicker, but it's terribly annoying. Since with any movement there is a miscalculation and these points are constantly changing on the edges of different blocks. 

Therefore, I will leave my shader settings where the problem is clearly visible.

**Steps to Reproduce**
Turn on the night in reading mode, go down into the caves, look for areas where there is little light.
rubidium-extra-0.5.4.3+mc1.20.1-build.121.jar
connectedglass-1.1.11-forge-mc1.20.1.jar
embeddium-0.3.29+mc1.20.1.jar
embeddiumplus-1.20.1-v1.2.13.jar
oculus-mc1.20.1-1.7.0.jar

Insanity-Shader-Universal-v1.650.zip
[Full-test-Insanity-Shader-Universal-v1.650.zip.txt](https://github.com/user-attachments/files/16625146/Full-test-Insanity-Shader-Universal-v1.650.zip.txt) - You can import shader settings from windowed mode.

![image](https://github.com/user-attachments/assets/e71b7b91-a625-4db7-9200-72dfe4b9fd9b)

**Screenshots**
### Open the screen to full screen, so you can see the problem better.
![image](https://github.com/user-attachments/assets/b2883f24-ad53-48cf-8603-c9d0dee67310)
![image](https://github.com/user-attachments/assets/e13c562c-9fd9-44a6-a167-5f6c16439b5b)
![image](https://github.com/user-attachments/assets/be40ff58-b928-443f-aae4-dfb998d17d78)
![image](https://github.com/user-attachments/assets/bf61ec1c-00e4-421a-bb08-78313dfea90e)

**Comment by SuperMartijn642** [comment]
I can indeed reproduce the issue, however it seems to simply be caused by having a large texture atlas.
The same issue occurs when installing a resource pack with large textures such as [Faithful 64x](https://modrinth.com/resourcepack/faithful-64x) together with just Embeddium, Oculus, and the Insanity Shader shader pack.
This would indicate the issue is unrelated to Connected Glass. Please report the issue to Oculus.

**Comment by Krimatoria** [comment]
> I can indeed reproduce the issue, however it seems to simply be caused by having a large texture atlas. The same issue occurs when installing a resource pack with large textures such as [Faithful 64x](https://modrinth.com/resourcepack/faithful-64x) together with just Embeddium, Oculus, and the Insanity Shader shader pack. This would indicate the issue is unrelated to Connected Glass. Please report the issue to Oculus.

And yes, indeed, something else breaks the textures.
