### ISSUE TITLE
[Question] NOT WORKING!!!

### ISSUE THREAD

**Issue by Vygrach** [SuperMartijn642/ConnectedGlass#76]
**Question**
Hello, I want to ask what should I do if your mod doesn't work for me. It was working perfectly normally for me before, but after the last update it stopped working and I'm very sorry because it's a very good gadget. I know it has to have Fusion mode for it to work, but even with that it doesn't work, so what should I do? do I have to add anything else to remove or how to proceed?
![Snímek obrazovky 2024-08-17 180720](https://github.com/user-attachments/assets/32c9c13e-289f-4b3b-a0ca-07f9d0cf4645)
![Snímek obrazovky 2024-08-17 180813](https://github.com/user-attachments/assets/29e29494-83e0-4c58-9650-67a47dbe28ec)

**Comment by SuperMartijn642** [comment]
Are you using the blocks added by Connected Glass?

**Comment by Vygrach** [comment]
> Are you using the blocks added by Connected Glass?

aha, somehow I overlooked or forgot that it has to be crafted, I'm sorry and thank you for the answer
