### ISSUE TITLE
[Question] ... Is it possible to remove the pixels on the glass?

### ISSUE THREAD

**Issue by QianMuu** [SuperMartijn642/ConnectedGlass#80]
**Question**
...

As requested, I added the following modules:
connectedglass-1.1.12-fabric-mc1.21
fusion-1.1.1-fabric-mc1.21
indium-1.0.35+mc1.21
sodium-fabric-0.5.11+mc1.21

I remember it can remove glass pixels, but is it not set now?

![aed651b5-d4a2-4473-8317-7189aa4a754e](https://github.com/user-attachments/assets/9ac78496-d0c1-462a-a827-333c11b5b840)

**Comment by SuperMartijn642** [comment]
Just use the clear glass?
