### ISSUE TITLE
[Bug] ...Invalid path

### ISSUE THREAD

**Issue by Fochy69** [SuperMartijn642/ConnectedGlass#83]
**Version Info**
- Minecraft, 1.21.1
- Connected Glass, 1.1.12

**Description of the Bug**
Log Error for path of dyes

**Steps to Reproduce**
Load mod/unload mod

**Screenshots**
No black dyes featured in screen shot due to having corrected them, :), by changing recipes. ( from "c:[colour]_dyes" to "minecraft:[colour]_dye")

[10:51:00] [main/WARN]: Not all defined tags for registry ResourceKey[minecraft:root / minecraft:item] are present in data pack: c:blue_dyes, c:brown_dyes, c:cyan_dyes, c:gray_dyes, c:green_dyes, c:light_blue_dyes, c:light_gray_dyes, c:lime_dyes, c:magenta_dyes, c:orange_dyes, c:pink_dyes, c:purple_dyes, c:red_dyes, c:white_dyes, c:yellow_dyes

**Comment by SuperMartijn642** [comment]
What modloader are you using?

**Comment by Fochy69** [comment]
Sorry, knew i'd miss something... Fabric

**Comment by SuperMartijn642** [comment]
Hmm I checked on Fabric 1.21.1 and got no such errors. These tags are legacy Fabric tags and are supposed to simply redirect to the new tags.
What version of Fabric API are you using? Could you share the `logs/latest.log` logs?

**Comment by Fochy69** [comment]
minecraft 1.21.1
Fabric loader 0.16.7
fabric api 0.106.0
 
latest log would be of no use as I have changed all the recipes. ( from "c:[colour]_dyes" to "minecraft:[colour]_dye") making the item singular rather than plural and the "c:" or "#c:" to "minecraft:" so don't get it anymore.
The original msg is all the error used to be, always after the recipe and advancements loading 

Might just be that my system "path" is not so open as most. As far as I know it had no effect on any playing issues but had only used in creative so couldn't say if the recipes would work in survival. More a case of finding it in the log and pointing it out just to keep things tidy.

**Comment by SuperMartijn642** [comment]
Just tried with Fabric API 0.106.0 to be sure and there seem to be no recipe errors 🤷‍♂️

**Comment by Fochy69** [comment]
In which case put it down to my system having a dodgy "path". I don't get that error in the log file now so as far as i'm concerned it's dealt with. Never seemed to cause any problems other than the error in the log. Bloody gremlins :)
