### ISSUE TITLE
Typo in modrinth description

### ISSUE THREAD

**Issue by linusvdv** [SuperMartijn642/ConnectedGlass#84]
Typo in the word install
![image](https://github.com/user-attachments/assets/4dd7444b-13a2-46ef-b8aa-16d4bded0bce)
Sodium ignores the Fabric rendering API. To solve this **~~isntall~~ install** [Indium](https://modrinth.com/mod/indium).

**Comment by SuperMartijn642** [comment]
Updated it 👍
